import { spawn } from 'node:child_process';
import { chromium } from 'playwright-core';
const server = spawn('npx', ['serve', 'dist', '-l', '4174', '-n', '-L'], { stdio: 'ignore' });
await new Promise((r) => setTimeout(r, 1500));
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto('http://127.0.0.1:4174/');
await page.keyboard.press('Tab');
const skip = await page.evaluate(() => document.activeElement.textContent.trim());
await page.keyboard.press('Enter');
const afterSkip = await page.evaluate(() => location.hash);
await page.focus('#menu-open'); await page.keyboard.press('Enter');
const openState = await page.evaluate(() => ({ expanded: document.getElementById('menu-open').getAttribute('aria-expanded'), focus: document.activeElement.id, locked: document.documentElement.style.overflow }));
for (let i = 0; i < 8; i++) await page.keyboard.press('Tab');
const stillInside = await page.evaluate(() => !!document.activeElement.closest('#mobile-menu'));
await page.keyboard.press('Escape');
const closed = await page.evaluate(() => ({ expanded: document.getElementById('menu-open').getAttribute('aria-expanded'), focusRestored: document.activeElement.id, scrollFreed: document.documentElement.style.overflow === '' }));
await page.focus('details:first-of-type summary'); await page.keyboard.press('Enter');
const faqOpen = await page.evaluate(() => document.querySelector('details').open);
await page.goto('http://127.0.0.1:4174/contact');
await page.click('#f-submit');
const formErr = await page.evaluate(() => ({ alert: document.getElementById('form-alert').textContent, alertVisible: !document.getElementById('form-alert').hidden, invalid: [...document.querySelectorAll('[aria-invalid="true"]')].map((e) => e.id), focus: document.activeElement.id }));
const mapBtn = await page.evaluate(() => { const b = document.getElementById('map-load'); b.focus(); return { visible: !b.hidden, focused: document.activeElement === b }; });
console.log({ skip, afterSkip, openState, stillInside, closed, faqOpen, formErr, mapBtn });
await browser.close(); server.kill(); process.exit(0);
